default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  port: 3306

development:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME_DEVELOPMENT'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  host: 127.0.0.1
  database: <%= ENV['DB_NAME_TEST'] %>
  password:
